### ISSUE TITLE
ESBuild/Vite unsupported due to top-level await requirement

### ISSUE THREAD

**Issue by ESchouten** [Dezinater/osrscachereader#4]
Seems like bundlers using ESBuild like Vite are not able to use this library since ESBuild does not support top-level awaits which the used bzip2 library @foxglove/wasm-bz2 is using. Any solution to this? Or do we have to swap out the bzip2 library?

Error:
```
[ERROR] This require call is not allowed because the imported file "vite-plugin-wasm-namespace:.../node_modules/.pnpm/@foxglove+wasm-bz2@0.1.1/node_modules/@foxglove/wasm-bz2/wasm/module.wasm" contains a top-level await

    node_modules/.pnpm/@foxglove+wasm-bz2@0.1.1/node_modules/@foxglove/wasm-bz2/wasm/module.js:52:29:
      52 │     const wasmPath = require("./module.wasm");
         ╵                              ~~~~~~~~~~~~~~~

  The top-level await in
  "vite-plugin-wasm-namespace:.../node_modules/.pnpm/@foxglove+wasm-bz2@0.1.1/node_modules/@foxglove/wasm-bz2/wasm/module.wasm"
  is here:

    vite-plugin-wasm-namespace:.../node_modules/.pnpm/@foxglove+wasm-bz2@0.1.1/node_modules/@foxglove/wasm-bz2/wasm/module.wasm:45:27:
      45 │ const __vite__wasmModule = await initWasm({ "env": { _emval_new_object: __vite__wasmImport_0_0, _emval_decref: __vite__wasmImport_0_1, _emval_new_cstring: __vite__wasmIm...
         ╵                            ~~~~~
```

**Comment by Dezinater** [comment]
Sorry but I don't really know alot about Vite/ESBuild so it might be hard for me to help. I've asked in the foxglove slack about this problem and they said "Not familiar either but I don’t think this issue is specific to the foxglove library because it claims there is a top level await in what appears to be code generated by vite itself (not the original .wasm file in the library)"

I've only been testing this library with webpack and it doesn't take too much to get it working there so I'm thinking there's probably a simple fix to this

Would this project maybe help/fix the problem?
https://www.npmjs.com/package/vite-plugin-wasm

Is there a project you have that I can clone to mess around with and see if I can fix the issue?

**Comment by ESchouten** [comment]
I ran the Load NPC tests which loads the cache, all bz2 compressed idx files returned the same UInt8Array with wasm-bz2 as with compressjs. Will open a PR.

**Comment by ESchouten** [comment]
Demo project here: https://github.com/ESchouten/svelte-osrscachereader
Pinned osrscachereader>web-worker dependency to 1.2.0, 1.3.0 causes some import error.
Added vite-plugin-wasm and vite-plugin-top-level-await, excluded env and wasi_snapshot_preview1 from dependency optimisation which made them disappear.
